### ISSUE TITLE
Mature Infrastructure

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#121]
* Infrastucture setup (possibly Terraform for code as infrastructure).
* Deployment (e.g. make a command to deploy to QA and to deploy to production safely, and to rollback) ~ Being addressed in https://github.com/penny-university/penny_university/issues/184
* Error logging (like sentry)
* Performance metrics
  * Response time against the slack 3second limit!
* Alerting
* Logging (like kibana)
* Analytics (like Google Analytics)
* Documentation (Like how to setup up a dev, qa, and production environment)
* Backups (nightly `heroku pg:backups`?)

**Comment by sburns** [comment]
Unfortunately good environments cost money. Any kind of budget on this stuff? 

Also if possible I'd suggest thinking not about specific, named environments, but rather "N+1" where 1 is production and N is the number of in-flight bundles of work. Said another way, every PR should get as much of a separate sandbox as possible. Some things are very hard/slow to duplicate like databases so I tend to share them across "PR sites" and leave a dedicated db for prod. This could be difficult given the nature of slack and how it binds slack apps.

**Comment by sburns** [comment]
Also you're talking about but not saying secret management (sentry DSN, GAnalytics ID, etc). That's always...fun.

**Comment by JnBrymn** [comment]
I was hoping you were going to chime in here Scott! You've done this type stuff lots more than I have. So keep an eye on us and let us know if you see any problems we can render. Let us get just a little further and we might call you in for a Penny Chat audit of our systems!

Regarding the N+1, amazingly we kinda have that right now :D. It's free to set up a new slack team and free to start up a new heroku app, and so far that's all we need! The DB is going to be somewhat problematic though because we only have realistic data in the production database. But I wonder if there's a way to restore a production backup to our individual staging environments. For a limited time we are small enough that that makes sense. That will buy us enough time to find a longer term solution.

**Comment by Raab70** [comment]
You could setup nightly backups (I don't know anything about heroku so I'll describe how I'd do it in K8s). Create a cronjob that nightly dumps a prod DB to something like GCS/S3. Then you can have a startup script (init container in k8s speak) on dev instances that downloads the latest backup and loads it into the DB before starting the application.

**Comment by JnBrymn** [comment]
That's not a bad idea @Raab70. I'll add that to the description as as reminder for later.

**Comment by sburns** [comment]
I believe heroku makes it simple to clone a DB from another?

**Comment by JnBrymn** [comment]
Actually... I can just run `heroku pg:backups:capture -a penny-university`. Heck... why not stick that in a deploy script!?

**Comment by nchouard** [comment]
@JnBrymn I think we can close this ticket considering all of our deploys are automated? Otherwise this feels like it will be a ticket forever... "Mature" is pretty vague 😛
