### ISSUE TITLE
Update Home Page copy

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#123]
1) "A Peer To Peer Learning Community" -> "The Social Learning Community" ?
2) In the second block we're owning culture that stretches back 250 years... it would probably be good to make is sound like we're influenced by/encouraged by, rather than we're the same thing.

**Comment by nchouard** [comment]
@JnBrymn Do we still want to do this? If you want to provide the copy here then anyone can pick up the issue and update the home page.

**Comment by JnBrymn** [comment]
It's been fine this way for a year, and the flavor of PennyU is changing, so let's hold off on this and update it when we have a more prominent public presence.
