### ISSUE TITLE
Update the invitation posts with a list or count the members attending.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#127]
Invitation posts are created when a penny chat invitation is shared. They look like this
![image](https://user-images.githubusercontent.com/566533/74613123-38d39a00-50d1-11ea-9c6e-b0eb8440c3fb.png)

When someone clicks an RSVP button it would be great to update the invitation post with information about who is going. If the attendee list is getting too long, then just list the number of people.

One challenge is that the invitation is delivered to several places and they all need to be updated. Probably the best way to do this is to save some sort of identifier corresponding to the slack message at the time they are posted (save this in the PennyChatInvitation _not_ the PennyChat). Then at update time, repost the invitations with the correct information.

**Comment by nchouard** [comment]
PR was closed but not the issue
