### ISSUE TITLE
Incorporate public google doc into penny chat invitation

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#131]
We are trying to guide people to collaborate and capture proof of the things they are learning. One fantastic way to do this is with a shared doc. The shared doc also serves as a great starting point to Penny chat follow-ups.

Make it easy for organizers to include a shared google doc. (Maybe a check box in the create?)

Similar to https://github.com/penny-university/penny_university/issues/130

**Comment by nchouard** [comment]
@JnBrymn Do we will want to do this? We could do it using the google integration, but it would require additional scopes that the users grant.

**Comment by JnBrymn** [comment]
I'm ok with closing this and letting it come back to us when it wants to.
