### ISSUE TITLE
Get list of upcoming penny chats

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#133]
# Description
Users need a way to view upcoming penny chats that they were invited to. For now, we will scope this to just the slack bot.

## Requirements
- [ ] Create a new bot command, `/penny upcoming`, which posts an ephemeral message containing a list of upcoming penny chats the user was invited to
- [ ] Include the title, date, and organizer of the penny chat in the list
- [ ] The list of chats should include one's the user was directly invited to, and chats that were posted in public channels

**Comment by JnBrymn** [comment]
Thanks for making this! I added some of my thoughts to the description. Also I think I'm going to start using labels for our Issues. `/penny chat` and `web-app` so far. What do you think?

**Comment by JnBrymn** [comment]
Marking as good first issue b/c it's pretty independent of other stuff. Though this is probably a good first issue for someone that knows a good deal about react already.

**Comment by nchouard** [comment]
@JnBrymn While ideally we will also have this in our web app, adding it to both the web app and the bot feels like a pretty large scope. I'm going to remove the `web-app` label and we can create another ticket for that later.

**Comment by JnBrymn** [comment]
Closing. Open back up for discussion if you think we need this now.
