### ISSUE TITLE
Set up Postgres and Dockerize

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#14]
* Set up Postgres so that it works from a Docker container but it's data is persisted in a Docker Volume
* Fix logging so that log files don't disappear when Docker container is stopped. (`/var/log`?)

**Comment by sburns** [comment]
We might handle this locally with compose, running postgres in another container. Obviously long-term we're running postgres outside of the normal web container anyways.

**Comment by nchouard** [comment]
I agree with Scott. I think we may as well just set up our postgres container now since we would most there in the future.

**Comment by sburns** [comment]
Maybe better in #penny-playground, but where is our infrastructure right now?

**Comment by JnBrymn** [comment]
# Original issue description
Build and run container in one terminal
```
docker build -t penny_u_django .
docker run -p 80:80 -e SLACK_API_KEY='' penny_u_django
```
In another terminal, shell in and save something to the db.
```
$ docker exec -it <get container with docker ps> /bin/bash
$$ ./manage.py shell
>>> from bot.models import User
>>> User.objects.create(slack_id=666)
>>> User.objects.first().slack_id  # prove it's there
```

Then kill and restart the server in the first terminal. Shell back in again and see that data is missing.
```
$ docker exec -it <get container with docker ps> /bin/bash
$$ ./manage.py shell
>>> from bot.models import User
>>> User.objects.first().slack_id  # prove it's not there
```

**Comment by Raab70** [comment]
Have you considered aurora serverless? It seems like a lot of work to set up a docker volume for postgres to run your own. Not to mention then you'll want to make sure the docker volume is mounted to an EBS device. The whole thing starts to bring up container orchestration when you're talking about running your own DB and application. I'd love to find some time to chat about your plans for this and #30 @JnBrymn.

**Comment by sburns** [comment]
I'm not against this idea @Raab70 but I think something like heroku postgres would be easier in the short term to operate. Plus we're not on AWS at all right now. If we migrate to E{C,K}S ever, we should consider this, but right now it's just a DO droplet.

**Comment by JnBrymn** [comment]
I'm not sure the route that PennyU should go, mostly because I don't what is involved in each possible option. However I do know the criteria that we should use in making the decision:

* Reduce unnecessary complexity – Despite my love of learning, we don't want to spend time learning and experimenting with new things when an existing approach is available and will do the job.
* Cater to the 75th percentile developer – If PennyU ever starts hiring, we want to hire smart people but not depend upon everyone having to be a genius.
* Don't mix interesting technical pursuits with product pursuits - Whatever gets PennyU there faster is the thing that we should do. Even if it's boring technically.

So where's that leave us? Despite what the title of this issues is here are my basic needs:

* We need code to be easily deployed to production w/ every merge to master.
* We need a persistent DB.
* We need logs to be persisted and available.

That it! So how do we get that? Maybe we can even drop some of the complexity we have already introduced.

**Comment by nchouard** [comment]
I have no issues with moving to Heroku for now. I've always found it incredibly easy to work with, and with a project of our current size (and size in the near-future). I agree with John that we should be focusing on speed of product implementation and release, and I think IaaS like Heroku is probably our best path towards that right now.

**Comment by Raab70** [comment]
Agree with @nchouard I did not realize we were off AWS so that's why I mentioned Aurora. Anything we build on AWS/GCP/Azure will be more complex and require documentation as opposed to using something like Heroku for now. Let's look at wiring that up and using their postgres service instead of running our own. 

Looks like we can do it with Github actions. Or are we not using that anymore? 

https://github.com/actions/heroku

**Comment by JnBrymn** [comment]
Perrrrrfect. I like where you guys are going with this. I think I have my
marching orders for this ticket - Heroku. I'll get a PR out soon.

**Comment by sburns** [comment]
I'm not necessarily advocating to use heroku for compute; heroku postgres is a separate service giving you a publicly available URL specifying a postgres database.
