### ISSUE TITLE
Fix Greeting Bot

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#147]
# Steps to reproduce
* Create temp email (https://temp-mail.org/en/)
* Invite temp email to Slack
* Join slack from the temp email using the web interface
* See that no greeting message is sent

**Comment by changhsinlee** [comment]
Tried reproducing this issue on my test slack channel and the greeting bot seems to work.

![image](https://user-images.githubusercontent.com/21176245/79405051-5bfbb800-7f61-11ea-94bc-8a86b3c61e69.png)

Should I test it in the Penny U channel as well with a temp email address?

**Comment by JnBrymn** [comment]
Actually... you know what. I've seen people filling out the form recently. That demonstrates that people are getting the form. It might be flakey!? But in that case this ticket becomes a low priority, flakey bug, that is only present in production, on a feature that needs a little overhaul anyway.

I'm closing :)  (I'm going to find some better issues now Chang)

**Comment by JnBrymn** [comment]
[](url)
