### ISSUE TITLE
Test creating and editing Penny Chats on frontend

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#149]
Creating and editing penny chats was added to the frontend, but no testing came along with it! Let's remedy this.

**Comment by deadbender** [comment]
Seems like this issue can be closed.

**Comment by JnBrymn** [comment]
I'm not able to edit my chat yet https://www.pennyuniversity.org/chats/178

**Comment by nchouard** [comment]
I think this was supposed to be creating and editing follow ups, not chats 😛

**Comment by nchouard** [comment]
Going to close this in favor of creating a larger ticket with lots of frontend tests
