### ISSUE TITLE
Set up python linting

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#15]
- [x] In .git/hooks prevent code from being pushed w/o passing PEP8.
- [x] Get everyone to add the new git hook
- [x] In .github/actions prevent code from being merged w/o passing PEP8.
- [x] Merge https://github.com/penny-university/penny_university/pull/53

**Comment by sburns** [comment]
The problem with git hooks is that they're ironically not version controlled. This is why [pre-commit](https://pre-commit.com) exists. In practice its...ok. I've found it's better to explain to authors that they should enforce pep8 in their editors and definitely enforce it in CI.

What do we think about enforcing _style_ with [black](https://pypi.org/project/black/)?

**Comment by JnBrymn** [comment]
Oh that's nice. When I was in golang we used gofmt. I initially bucked at something else controlling my formatting but then after all needless discussion of formatting went away I decided it was wonderful.

One annoying thing about black is the insistence upon `"` instead of `'`. I'm a wimp, but twice I've turned off my shift key one one side of my keyboard when I've started to get tendentious.

**Comment by sburns** [comment]
black is something i've absolutely set up in my editor to run on file saves. what ends up happening is that i just write a lot terribly-formatted junk and on save it's cleaned up real pretty.

**Comment by JnBrymn** [comment]
@nchouard can you stick this script at `penny_university/.git/hooks/pre-commit` ? 

This will make it so that right before git commits code, it will run pytest and flake8 (linter). Naturally, read over this and make sure you approve first.

```python
#!/usr/bin/env python
import sys

from flake8.main import git as flake8_run
import pytest

if __name__ == '__main__':
    print('\nRUNNING PYTEST')
    pytest_errors = pytest.main()

    print('\nRUNNING FLAKE8')
    flake8_errors = flake8_run.hook(strict=True)

    problems = flake8_errors + pytest_errors

    print(f'\nPytest error status {pytest_errors}, Flake8 error status {flake8_errors}.')
    if problems:
        print('NO COMMIT FOR YOU!\n')
    else:
        print('Proceeding with commit.\n')
    
    sys.exit(max(pytest_errors, flake8_errors))
```
