### ISSUE TITLE
Login flow for frontend.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#151]
When an un authed user takes an action that requires authentication, show them the authentication flow
First modal with an email form
   - Make a request to see if the user has an account
   -  If the user has an account,  request their password to make login request
   - If not show them a form requesting first name, lat name and password to make signup request

**Comment by JnBrymn** [comment]
Blocked on https://github.com/penny-university/penny_university/issues/213

**Comment by nchouard** [comment]
@CoreyAR The login flow will have to be updated with the updates from #223.
