### ISSUE TITLE
Fix confusing date filter in /penny chat reminder

### ISSUE THREAD

**Issue by changhsinlee** [penny-university/penny_university#157]
Steps to reproduce:

1. Set up a penny chat with `/penny chat` with someone at least 2 days out
2. on the day before the chat, check slack bot

**Comment by changhsinlee** [comment]
![image](https://user-images.githubusercontent.com/21176245/78092100-c2e37380-739c-11ea-90f6-7e99bf7fa3f1.png)

**Comment by JnBrymn** [comment]
found another `{{date_pretty}}`
