### ISSUE TITLE
Figure out how to deal with the relationship between `UserProfiles` and Django auth `Users`

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#168]
# Description
Historically we didn't require login so we didn't use the Django `User`. We instead used `UserProfiles` as the owner of things like `PennyChats` and `FollowUps`. A `UserProfile` is associated with a single slack. The original idea is that as we start associating `UserProfiles` in a one-to-one relationship with a person on a Slack workspace. But that person might be on several Slack workspaces, so a Django `User` would be associated with multiple `UserProfiles` and would serve to unify them.

That sounds good, but is leading to some confusing-to-reason-about code. Consider these situations:
* When I'm sending invites I will be contacting people via their slack_id - thus there must be a relationship between `UserProfile` and `PennyChatInvite`.
* BUT wouldn't it be cool to eventually invite people via email address - in this case we won't have their slack id - this is a relationship between a Django `User` (or maybe even just an email address?) and a `PennyChatInvite`
* Eventually people will come to the website and find their own `PennyChats` - thus a Django `User` is the logical owner
* But you might also want to filter things down to a particular Slack identity - so we need `UserProfile too.`
* And how are ALL these associations made? Participation I suppose. Should Participations have foreign keys to both UserProfile and AuthUser?

*Key places to look at* include:
* `UserProfile.objects.get`
* `UserProfile.objects.get_or_create`
Because these presume that only one `UserProfile` will be retrieved. These will often cause exception when we have more than one Slack account.

# TODO
* Figure out where we currently are:
  * Identify all relationships between `Users` and `UserProfiles`.
  * Identify all relationships between `Users` and other models.
  * Identify all relationships between `UserProfiles` and other models.
  * Finally, anticipate some future relationships and usages.
* Find a pattern
* Propose a solution.
* Create tickets to solve it.

**Comment by CoreyAR** [comment]
@nchouard I believe you took care of this with PR#215
