### ISSUE TITLE
Create /me endpoint

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#171]
Create an endpoint to get the login user using the Token passed back in the authorization header.

**Comment by CoreyAR** [comment]
I found our auth library comes with this out of the box so I used that for now
https://dj-rest-auth.readthedocs.io/en/latest/api_endpoints.html#basic
`/dj-rest-auth/user/`

**Comment by nchouard** [comment]
Tabling this for now as we discussed in slack.

**Comment by nchouard** [comment]
I'm closing this issue and creating one to fit fetching information for any user instead.
