### ISSUE TITLE
Update Website per Ammi's Recommendations

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#18]
* [x] Fonts - slab (maybe roboto for headers and a sans font for paragraph)
* [x] Call-to-action - stick "join us" button in nav bar or maybe add button under Penny University title
* [x] Tab title - misspelling
* [x] Favicon - Smaller version of logo
* [x] Put placeholders for social media in the top nav
* [ ] Align nav text (title in center, social media aligned vertically)

**Comment by nchouard** [comment]
Closed by #26
