### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#187]
# Description
Our users need a page where they can see the Penny Chats that they participated in. Other users, whether authenticated or not, should be able to visit and view these pages.

 Additionally, authenticated users can open a modal to edit their details such as name.

## Requirements
- [ ] Users can navigate to pages with details about each user. This page will display a list of the Penny Chats they participated in.
- [ ] Users can edit their own details such as name and interests.

**Comment by CoreyAR** [comment]
I'd suggest breaking this ticket out into two parts for the benefit of a lean MVP.
We can include profile page where an authenticated user can edit their own page in the MVP, this is a necessary feature for a user to manage how they authenticate and appear on the site.

Interests sounds alike a good post MVP feature because we don't have anything built around this to. I'd also move lists of chats and social sharing to post MVP as features we can prioritize based on feedback.

**Comment by nchouard** [comment]
I'm fine with moving interests and sharing to post MVP. I think that lists of a user's chats is an important feature for our returning users (people who have used the forum before), because it lets them see their history in a new, nicer way. It can be used as a reminder for how they've gotten value from Penny U. @JnBrymn what are your thoughts?

**Comment by JnBrymn** [comment]
I agree that this ticket is a little larger than a single task. And I think the ordering that Corey has in mind makes sense to me. I like the idea of ruthlessly prioritizing work that leads us to getting this in front of other people's eyes. I think we need the MVP to prove that we can ship software! But I agree with Nick's sentiment that the "my chats" page will bring a lot of value to users. That should be a fast follow-on to the MVP.

Also, regarding the MVP. I'm thinking that after this first deliverable, we will have lots of fast follow-on updates to give our current users. However, once we've vetted several waves of these updates, we will eventually have something more like a General Availability of the platform that we advertise to a broader set of potential users. That might try some actual marketing. That's when I want to hit Hacker News.
