### ISSUE TITLE
User receives greeting when invited, not when they join

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#20]
A user will receive the greeting message as soon as they are invited, before they even join the workspace. No one has responded to our greeting messages, possibly because they haven't actually seen the message, and it got buried beneath the Slackbot messages.

* Is it possible to send for a different event (rather than "joined channel")?
* Is it possible to send a direct message from the Penny App (rather than from Slackbot)?

**Comment by JnBrymn** [comment]
> Is it possible to send a direct message from the Penny App (rather than from Slackbot)?
That's a neat idea.

**Comment by JnBrymn** [comment]
Low priority. Closing. We'll revisit the entire feature soon enough.
