### ISSUE TITLE
Migrate to Slack Conversations API before 2020.11.25

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#208]
* https://api.slack.com/docs/conversations-api?utm_medium=email&utm_source=newsletter&utm_campaign=fy21-Q205-changelog
* https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api?utm_medium=email&utm_source=newsletter&utm_campaign=fy21-Q205-changelog

**Comment by nchouard** [comment]
I just checked our codebase, and we do not have any of the deprecated methods in there anymore.
