### ISSUE TITLE
New users get several greeting messages

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#217]
# Description
While doing some testing I invited some new fake users and realized that they got several of our greeting messages.

### Steps to Reproduce
1. Use temp-mail.org to get a fake email address.
2. Using your staging environment, invite a new user.
3. As the new user, accept the invite. You should see two new messages immediately, and then possibly more over the next few minutes. One user I invited received 4 greeting messages.

<img width="894" alt="Screen Shot 2020-05-15 at 5 31 47 PM" src="https://user-images.githubusercontent.com/31971995/82101454-2407a200-96d2-11ea-8f3f-df11d595a169.png">

### Desired behavior
New users should only receive one greeting message.

**Comment by nchouard** [comment]
This only seems to be occuring in QA

**Comment by JnBrymn** [comment]
I just tried this in my QA w/ code from master and didn't get _any_ chat and nothing interesting in the logs.

In any case, I think it's time we reevaluated whether the feature and either fix it or get rid of it. Thus https://github.com/penny-university/penny_university/issues/258
