### ISSUE TITLE
Fix time localization issue during creation of Penny Chat

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#218]
# Steps to Repro
1. Live in Argentina, 2 hours east of central time.
2. Create a Penny Chat for 9PM
3. Ask a friend that lives in the central timezone to look at the invite time and see that it says 9PM

Expected: The Nashville person should see the time as 7PM because at creating time the TZ is localized to the person creating the event.

So effectively the time presented in the chat cards is localized to your time, but the penny chat modal time select box is erroneously localized to Nashville time.

**Comment by JnBrymn** [comment]
I don't know how this bug could be.

We get the timezone from the organizing user https://github.com/penny-university/penny_university/blob/0f51bcd7b1f985cc3e40293e44ba68c047dab78e/bot/processors/pennychat.py#L242

which we pull directly from slack https://github.com/penny-university/penny_university/blob/0f51bcd7b1f985cc3e40293e44ba68c047dab78e/bot/processors/pennychat.py#L216

And then we take the date _string_ that the user selected and localize it into their local time here https://github.com/penny-university/penny_university/blob/0f51bcd7b1f985cc3e40293e44ba68c047dab78e/bot/processors/pennychat.py#L269

**Comment by JnBrymn** [comment]
I don't know how this bug could be @CoreyAR. Are you sure I have the StR correct above?

We get the timezone from the organizing user https://github.com/penny-university/penny_university/blob/0f51bcd7b1f985cc3e40293e44ba68c047dab78e/bot/processors/pennychat.py#L242

which we pull directly from slack https://github.com/penny-university/penny_university/blob/0f51bcd7b1f985cc3e40293e44ba68c047dab78e/bot/processors/pennychat.py#L216

And then we take the date _string_ that the user selected and localize it into their local time here https://github.com/penny-university/penny_university/blob/0f51bcd7b1f985cc3e40293e44ba68c047dab78e/bot/processors/pennychat.py#L269

**Comment by nchouard** [comment]
IIRC this is not a bug. I remember speaking to Corey and his slack was set for Central time, which is why he saw it appear as 
Central.
