### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#28]
Having "Not Secure" next to our web address makes me sad 😢. Let's establish an SSL certificate and always redirect to HTTPS.

**Comment by Raab70** [comment]
Looks like if we are using heroku we won't have to run our own reverse proxy layer: https://devcenter.heroku.com/articles/ssl

**Comment by nchouard** [comment]
![Screen Shot 2019-09-19 at 9 47 24 AM](https://user-images.githubusercontent.com/31971995/65442175-54bc6380-ddf1-11e9-9260-bbb596554dc3.png)
I thought that HTTPS worked out of the box with heroku, but apparently there are some problems with it when using CNAMEs.

**Comment by JnBrymn** [comment]
Some progress tonight:
* https://www.pennyuniversity.org works 🎉 
* http://www.pennyuniversity.org works does not redirect to https://www.pennyuniversity.org works 😢 
* https://pennyuniversity.org fails to load entirely 😭 

However I've updated the google domains DNS to redirect @ to https://www - we'll see if that works by tomorrow
