### ISSUE TITLE
Research ideas for `/penny chat`

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#29]
# TODO
- [x] Turn this into an Epic ticket ~ https://github.com/penny-university/penny_university/issues/63

# Description
Within Slack, users need an easy way to create Penny Chat invites and share with others. Here is one possible workflow:

* User types `/penny chat`
* Penny app starts an interactive chat to ask user the date/time, topic, details, and people to invite. (Try creating a `/doodle` in Slack for inspiration.)
* Once the PennyChat has been created, the user will be given a notification of the PennyChat along with details. The user can accept or decline to join.
* Just before PennyChat, users are reminded of chat.
* Just after PennyChat, users are reminded to do their PennyChat review.

*Important Note:* this issue is not to actually build the full product, but instead it is to get all the pieces on the table. We will need to ask our users about the UX before the final implementation.

## Areas to research
* What database tables will we need?
* What new bot modules will we need? With the bot framework standup to the new stuff?
* How hard is it to create the bot conversation?

## Optional/related/future ideas:
* Public events can be added to a public Google Calendar.
* Organizer is notified as other users accept chat. Might be critical feature to guard against unexpectedly large group.
* Organizer can also check on chats with `/penny chat list` to see who is coming or who came to all their chats.
* Many PennyChats will use zoom or Google Hangouts. How can we incorporate this into reminders?

**Comment by JnBrymn** [comment]
@nchouard This ticket might be done since it says "research". I'd say either close it, move it to done, and create a new "build the thing" ticket. Or morph the main comment so that it outlines how you intend to build the thing.

**Comment by nchouard** [comment]
Follow up from initial release of penny chat bot:
- User isn't notified of own meeting.
- Store attendees instead of just invitees. (to do this we mush have invites agree to go)
- New Google calendar is created for each user… that's sad.

**Comment by nchouard** [comment]
Closing out some old issues
