### ISSUE TITLE
Update Interest Survey

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#293]
_Note: This is not an actionable issue until we agree on work involved and exit criteria._

# Ideas:
* Make the questions more concise.
* Remind people if they didn't answer.
* Send out a slack-wide survey so that everyone gets the questionnaire again..
* What can we do to use the data that people provide us? (Newsletters?)
* [Is this old send out script useful?](bot/management/commands/onboard_users.py:9) (if not, delete) 

# Context

## Here's what people currently see when they arrive:
![image](https://user-images.githubusercontent.com/566533/87746274-c2d57b00-c7b5-11ea-9e26-36a08d5a3f16.png)

## And if they click the button they get this modal:
![image](https://user-images.githubusercontent.com/566533/87746306-d8e33b80-c7b5-11ea-98e3-7964fb757db5.png)

## And when the fill out the modal they are introduced in #general 
![image](https://user-images.githubusercontent.com/566533/88872480-df26de00-d1df-11ea-921c-02e31906059f.png)

I bet we'd have more luck if we just had a "LET'S GET STARTED" button and no other text. We could always stick the text after they submit the modal.

**Comment by deadbender** [comment]
Brainstorming this as my 2nd issue of the day, let me know what you think.

### Initial Text

**Welcome to Penny University @user_id!**

Penny U is a social learning community built on a similar concept applied in the 17th century. Learn more about our name and history [here](https://www.pennyuniversity.org/#faqaccordion).

Chat with others in the existing channels (or make a new one!), and if you have something you want to teach someone or learn from someone else, organize a _Penny Chat_ and get in touch!

Ready to get started? Let the community know who you are!

button: **Get started!**

### Form

*All plain text inputs, temporary until we could do tags. Comma separated values could work, but I think if we narrowed it down to the primary subjects Penny U chats about in a select menu that might be helpful for testing out matchmaking.*

- What are you most knowledgeable about?
- What are you interested in?
- Where are you from?

### Post-Form

#### #general 

🎉 **Welcome to Penny University @user_id!**

{first_name} is interested in learning about X, Y, and Z, and can teach about X, Y, and Z! 🤔 If you have similar interests, go ahead and reach out for a _Penny Chat_!

#### #welcome-committee

{user_id} just joined and is interested in X, Y, and Z. Anyone want to setup a quick 15 minute chat on the [Intro to Penny U](https://docs.google.com/document/d/1j1C93Ojd-sIbX76mXhuizwOSc4wdk2pVywcNCRvDBas/edit)?

*Bot should auto react with a ✅ and ❌ emoji for users to click on. Once someone clicks ✅, the message will be edited to say:

`{user_id} just joined and is interested in X, Y, and Z. {welcome_member} has agreed to setup a quick chat with them on the Intro to Penny U!`

#### DM conversation

Congratulations! You've been introduced to the Penny University community and a member of our welcome committee should reach out soon to get you introduced with the basics. Feel free to go ahead and participate in some conversations, lurk, or reach out to specific users with similar interests! Just to recap:

- If you have something you can teach, then let it be known.
- If you have something you want to learn, then reach out to the community or to an individual and ask for help - then buy them a coffee, lunch, or jump on a video call for a _Penny Chat_.
- When your Penny Chat is complete, show your appreciation by posting a Penny Chat review in our [forum](https://pennyuniversity.org/chats) and teach the world a little bit of what you have learned. 

Want to learn more? Check out previous chat follow-ups on our [website](https://pennyuniversity.org/chats), check out our [FAQ](https://pennyuniversity.org), or ask some other users!

**Comment by JnBrymn** [comment]
Thanks for your feedback @deadbender, I think @nchouard will provide the best feedback since he was most interested in resurrecting this interaction, but I'll add some comments of my own.

* The goals have somewhat shifted for the form from what currently exists because rather than just appearing when someone arrives, they will be sent to everyone that hasn't filled out a form so that we can get a database of people's interests.
* I think a big problem with the existing one is that the intro text is just too long. So the size of your "Initial Text" is probably close to what it needs to be, but the content should probably be touched up. "built on a similar concept applied in the 17th century" isn't really helpful or motivating to the user. We'll have to think how to pack "how we do things here" into a tiny bit of text. We might remove the history lesson if it doesn't fit.
* The #welcome-committee messages aren't worth changing just yet. Once we get more people helping in there, then we can add more detailed content, but that's not "exportable engagement" because we can't export the welcome behavior.
* The direct message is something that's missing! If the into message is too long, then we can add _some_ of it to the DM. It's worth thinking about.

**Comment by nchouard** [comment]
My thoughts for the survey: it should be as short as possible.
## Initial Text
Something like:
"Penny University connects people who have similar interests in order for them to learn together. Add your interests so we can do the same for you."
*button*: Add Your Interests

The form might be able to stay the same for now. Right now our only option with Slack's API would be to do comma separated interests.

**Comment by nchouard** [comment]
Need to actually release this before closing this ticket.

**Comment by JnBrymn** [comment]
What is "releasing this"? Meaning send this survey to all users?

**Comment by nchouard** [comment]
Closing this because the interest survey _was_ updated. Plus, we have another ticket to reevaluate the greeting functionality.
