### ISSUE TITLE
Localize time on Penny Chat pages

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#312]
![image](https://user-images.githubusercontent.com/566533/88409266-543a8380-cd9a-11ea-9aea-b3a30ef38753.png)

If a user is logged out, then we don't have a way of localizing their time because we don't know it. In that case we need to find some nice way of presenting the timezone. Further, if someone is logged in, are we sure that the timezone is localized for them? Need to double check.

**Comment by nchouard** [comment]
We store times in UTC, and then it is localized based on the browser.
