### ISSUE TITLE
persist content in the browser so that it can be saved after sign-in

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#316]
Figure out how to persist content in the browser, so if someone is interrupted during an edit, the content will still be available after a page reload.

If we fix this then we can undo the preemptive save of followups to the db which is causing some problems. People tend to submit the form during the sign in process, NOT see the page update, and submit it multiple times so that when their email is validated, all of the submitted followups are visible.

**Comment by nchouard** [comment]
Was done but not closed
