### ISSUE TITLE
Deleting a followup makes the browser contents dissappear

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#324]
# Steps to Repo
1. Create a followup on one of the chats.
2. In a NEW window delete the followup.
3. After you confirm deletion, the contents of the page will disappear

# Expected behavior
Just deleting that Followup

**Comment by JnBrymn** [comment]
We need more frontenders. @nchouard how can we find someone new to work on this?

**Comment by nchouard** [comment]
Not sure, but I'm going to pick this one up because it'll bug me otherwise 😜
