### ISSUE TITLE
The ability to edit disappears

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#326]
# Steps to repro
1. Create a /penny chat and submit
2. In #slackbot click the edit button (the message with the edit button goes away)
3. Rather than submitting the modal, click close
4. A new edit doesn't pop back up :oh noes:

If it's possible, probably the best solution is to not delete the #slackbot edit message until we are ready with a new message to post.

**Comment by nchouard** [comment]
Do we need to delete the message at all? Since it is just a DM, I don't think it is a big deal if you see the history of your invites.

**Comment by JnBrymn** [comment]
That would be the easy fix! I'd be ok with that.
