### ISSUE TITLE
Create FAQ on the website

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#33]
# Description
Create a static HTML page on the website with content for our FAQ page.

## Details
Build a regular HTML page (using bootstrap styles) with content for the FAQ page. The url `/faq` should direct to this page.

## Notes
"what is a Penny Chat?" "How do I set one up?" "Whats a Penny Chat review? How do I write one?"

Writing sample:
https://docs.google.com/document/d/1z_4V5FOSlO6TJhwhTqKhd4yMYyAGt5V2lFJmYuVkQyU/edit

FAQ Page write-up: https://docs.google.com/document/d/1R9iIHjggCjp8nLfEyHDhovHpD7axUlM49IjfYkUBsTU/edit

**Comment by nchouard** [comment]
https://docs.google.com/document/d/1z_4V5FOSlO6TJhwhTqKhd4yMYyAGt5V2lFJmYuVkQyU/edit
