### ISSUE TITLE
Not everyone is getting updates from Penny

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#338]
User Derek Buckley isn't getting updates from Penny and Penny isn't even in their left nav:

![image](https://user-images.githubusercontent.com/566533/91071023-44ae9480-e5fd-11ea-8690-3d2067013d09.png)

It is in mine.
![image](https://user-images.githubusercontent.com/566533/91071040-4b3d0c00-e5fd-11ea-9f7d-3f75c79ebe80.png)

_Why?_ (And how on earth do we debug this?)

**Comment by JnBrymn** [comment]
According to Derek it just magically appeared! We still need to check if it's not present when people sign up because that's how we first contact them. @nchouard if you're still working with the onboarding, do you want to check this out? If it's present when you sign up as a new user then I guess we can close this.

**Comment by nchouard** [comment]
Yep, I'll do that.

**Comment by nchouard** [comment]
Tried with a new user who got the Penny bot message right away! Closing
