### ISSUE TITLE
Destroy our Integration Tests and build them anew with cypress

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#340]
Our existing slack integration testing is painful to the point of not being useful. Consider using https://github.com/microsoft/playwright to set up automation testing. Playwright provides a Javascript API for interacting with a headless browser. We can use this to create integration test through the _real_ Slack web UI rather than recording traffic.

This is actually a better integration test because it uses Slack itself.

**Comment by coreyar** [comment]
For integration tests I'd recommend Cypress. The developer experience is great and it provides a nice setup for TDD.

https://www.cypress.io/

**Comment by JnBrymn** [comment]
Pr in #375
