### ISSUE TITLE
Penny Chats in wrong order on profile page

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#362]
# Steps to Reproduce
~I _think_ this works:~ I tried this in my QA slack and couldn't reproduce the effect.
* Create 2 Penny Chats, Chat A for 10 minutes from now and Chat B for 20 minutes from now.
* Change Chat A to be 30 minutes from now.
* Load the profile page see that the Chat B is first and Chat A is next even though Chat A is further into the future and is even labeled as such. 

[This is definitely a front-end bug](https://github.com/penny-university/penny_university/issues/362#issuecomment-717681746)

Example of mis-ordered chats:
![image](https://user-images.githubusercontent.com/566533/93777028-dc49d780-fbe9-11ea-9edf-4fd3c0989cee.png)

**Comment by nchouard** [comment]
To whoever ends up taking this on: the first thing you should do is figure out whether this is a frontend or a backend bug. My _feeling_ is that it is a backend bug, because that is where we decide the ordering. You could verify by just making a request to the API (using Postman or curl) and seeing the order in which the chats return.

**Comment by JnBrymn** [comment]
@deadbender tried directly hitting the API tonight for my profile page and saw that the items consistently came out correctly ordered from the API and were consistently out of order on my profile page. So I think this is a frontend bug. We did notice that there were no misorderings on the /chats web page, but only on the /profile/3 page.

**Comment by JnBrymn** [comment]
### more clues
On my profile page, here's what I see in the network:
![image](https://user-images.githubusercontent.com/566533/97388279-c47b0880-18a5-11eb-95eb-8574826fa349.png)

Each `?` preceeded line is a call to the `api/chats` endpoint. Questions:
* Why are there 3 calls?
* Why are we calling with `upcoming_or_popular`? This is only supposed to be used on the /chats web page now.

And if I look at the Redux console I see
![image](https://user-images.githubusercontent.com/566533/97388268-bf1dbe00-18a5-11eb-9809-eedab406f1b4.png)

I can check the Actions tab and see that my "Suneethi" chat which should be first is appearing on the second CHATS_LIST_SUCCESS action.

Now looking back at the network tab, if I look at the results from the first `participants__user_id` call corresponds the the first results on the page which **don't include** a later chat that loads further down.

```shell
curl 'https://www.pennyuniversity.org/api/chats/?participants__user_id=3' \
  -H 'Connection: keep-alive' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://www.pennyuniversity.org/profile/3/' \
  -H 'Accept-Language: en-US,en;q=0.9,cy;q=0.8' \
  --compressed
```
The next `participants__user_id` request however _does_ include the missing chat. The only difference in the two requests is that the second has the `Authorization` header.

### root problem
Loading the /profile/X page makes multiple requests to the api/chats endpoint, only one of which is necessary. How can we keep the authenticated call to `api/chats/?participants__user_id=3` and remove the unauthenticated call as well as the call to `api/chats?upcoming_or_popular=true`

**Comment by JnBrymn** [comment]
This issue is closely related to https://github.com/penny-university/penny_university/issues/350
