### ISSUE TITLE
Automatically add to slack rather than just telling us the email address.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#39]
Currently, if the user goes to pennyuniversity.co and clicks the Join button, their email will be sent to slack and then we will add them manually. Let's just have a machine do the whole process (though still notify admins in slack). And let's also post a notification in the #welcome-committee channel.

**Comment by nchouard** [comment]
https://stackoverflow.com/a/36114710 At first, I thought there wasn't a  way to do this via API. Turns out that it's just an "undocumented" feature.

**Comment by nchouard** [comment]
The Slack Client doesn't have a helper method for it, so we will have to make one ourselves.

**Comment by JnBrymn** [comment]
@changhsinlee THIS would be an awesome thing for you to work on.

**Comment by nchouard** [comment]
https://api.slack.com/methods/admin.users.invite updated api method I found

**Comment by changhsinlee** [comment]
> https://api.slack.com/methods/admin.users.invite updated api method I found

Looks like this API is only available with Enterprise Slack 😢?

https://api.slack.com/enterprise/managing

> The following list of features and APIs are available in Enterprise Grid workspaces only.

**Comment by changhsinlee** [comment]
Just looked into https://github.com/outsideris/slack-invite-automation

It turned out they also use the legacy token: https://api.slack.com/legacy/custom-integrations/legacy-tokens so it will become useless after May 5th.

**Comment by JnBrymn** [comment]
It might very well be that Slack intentionally prevents this behavior. In that case we'll have to plan around it somehow.

**Comment by changhsinlee** [comment]
I'll work on the permanent link idea + automate the welcome message

**Comment by JnBrymn** [comment]
![image](https://user-images.githubusercontent.com/566533/79936798-eb9bdd80-841d-11ea-864d-33de205f42ae.png)

The current, _un_-automatic sign-up flow is you click JOIN on pennyuniversity.org, and then a modal pops up and asks for your email. (And then the rest is manual.)

On thing we could do is to link the JOIN button directly to the Slack self sign-up. But that is a jarring change for the user.

Instead I proposed that we can change the text in the modal and let them know that we're sending them to a Slack self sign-up page.

Instead of "Give us your email address and we will add you to our Slack group. You will also be able to add your own Penny Chat Reviews to our Google Forum." Say "The Penny University community hangs out in Slack. Click the button below to be taken to the slack sign-up page."

**Comment by JnBrymn** [comment]
BTW you're correct that this is really 2 tickets 

1. The automated sign-up (and cleaning up whatever code we no longer use)
2. After people join automatically posting in the welcome room.

Feel free to split this into two tickets if you'd like.
