### ISSUE TITLE
Use gravatar for image

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#85]
See
* [python creation for gravatar URL](https://en.gravatar.com/site/implement/images/python/)
* [gravatar API](https://en.gravatar.com/site/implement/images/)

In particular, note that we have intentionally return a default image or a 404 if the person doesn't have a profile. It might be interesting to see how many of our users have a gravatar.

**Comment by nchouard** [comment]
@JnBrymn Is this for an image in the web app? I feel like at some point we might just do a front end redesign, at which point considering this might make sense. In the meantime, it doesn't really have a place in our backlog because it's not a priority and it probably won't become one any time soon.

**Comment by JnBrymn** [comment]
If you love something, then let it go. If it comes back to you, then it will be yours forever.
