### ISSUE TITLE
Make dev_settings.py, prod_settings.py

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#91]
At eventbrite, `settings` was a package folder rather than a standalone filed. The folder used the `__init__.py` to hold all the settings but then had `dev_settings.py` and `prod_settings.py` etc. to hold the details specific to each of these environments. IICR the `dev_settings.py` and `prod_settings.py` imported the `__init__.py` and then we just specified which setting file to use at startup time.

That said, I think I am remembering something incorrectly because I think I just defined a circular import! So... mumble mumble hand wave.

**Comment by nchouard** [comment]
This was closed by #89. You can specify the settings file to use with `export DJANGO_SETTINGS_MODULE=penny_university.settings.prod.py`.
